# Generated by Django 6.0.3 on 2026-03-17 19:29

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCatalogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Introduction text shown at the top of the catalog')),
                ('catalog_image', models.ForeignKey(blank=True, help_text='Header image for this course category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CourseDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(help_text='Short description shown in the catalog listing')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in EUR (e.g., 29.99)', max_digits=6)),
                ('instructor', models.CharField(blank=True, help_text='Name of the course instructor', max_length=255)),
                ('course_content', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('learning_point', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'help_text': 'Section heading'}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Rich text content'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Full-width image'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "A single 'What you will learn' item"})}, help_text='Detailed course content built from blocks')),
                ('course_image', models.ForeignKey(blank=True, help_text='Main image for the course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
