# Generated by Django 6.0.3 on 2026-03-28 19:54

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contactpage_faqpage_pricingpage_contactformfield_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingpage',
            options={'verbose_name': 'Pricing Page'},
        ),
        migrations.AlterField(
            model_name='pricingpage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text="Tier name, e.g. 'Explorer', 'Learner', 'Professional'", max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Monthly price in EUR. Use 0 for free tier.', max_digits=6)),
                ('description', models.CharField(blank=True, help_text="Short tagline, e.g. 'Full access to one category'", max_length=200)),
                ('features', wagtail.fields.RichTextField(help_text='Feature list — use bullet points (ul) in the editor')),
                ('is_featured', models.BooleanField(default=False, help_text="Highlight this tier as 'Most Popular' (only set one!)")),
                ('button_text', models.CharField(default='Buy now', help_text="Text on the CTA button, e.g. 'Get started', 'Buy now'", max_length=30)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe Price ID (e.g., price_1Abc123...). Leave blank for free tier.', max_length=100)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='pages.pricingpage')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
